#!/usr/bin/env python3
"""Report tenant-scoped tables that are missing RLS protection.

Usage:  python check_tenant_isolation.py "$DATABASE_URL"

Exits 1 if any table has a tenant_id column but lacks ENABLE ROW LEVEL
SECURITY, FORCE ROW LEVEL SECURITY, a policy, or an index on tenant_id.

Autogenerated Alembic migrations never emit RLS, so a table can look
correct in the model layer and be completely unprotected in the database.
This catches that gap.
"""
import sys

# The report uses '✗'. Windows consoles default to cp1252, which cannot encode
# it, and the script dies mid-report with a UnicodeEncodeError instead of
# printing findings. Force UTF-8 and degrade rather than crash.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import psycopg
except ImportError:
    sys.exit("pip install 'psycopg[binary]' to run this check")

# Tables that legitimately have no tenant scope. Keep this in sync with the
# exemption list in the architecture doc (§4.7); an addition needs a reason.
#   tenants, tenant_phones, plans  — the tenant is the row
#   outbox                         — cross-tenant by design; poller uses BYPASSRLS
#   inbound_messages               — written before the tenant is known
#   alembic_version                — migration infrastructure
# 'orphan_statuses' is deliberately absent: v3 §A.2 moved it to a Redis key with
# a TTL, so a table by that name would be a mistake, not an exemption.
EXEMPT = {"tenants", "tenant_phones", "outbox", "plans",
          "inbound_messages", "alembic_version"}

QUERY = """
SELECT c.relname                                   AS table_name,
       c.relrowsecurity                            AS rls_enabled,
       c.relforcerowsecurity                       AS rls_forced,
       (SELECT count(*) FROM pg_policy p
          WHERE p.polrelid = c.oid)                AS n_policies,
       EXISTS (SELECT 1 FROM pg_attribute a
                WHERE a.attrelid = c.oid
                  AND a.attname  = 'tenant_id'
                  AND NOT a.attisdropped)          AS has_tenant_id,
       EXISTS (SELECT 1 FROM pg_index i
                JOIN pg_attribute a
                  ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
                WHERE i.indrelid = c.oid
                  AND a.attname = 'tenant_id')     AS has_tenant_index
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r' AND n.nspname = 'public'
ORDER BY c.relname;
"""


def main(dsn: str) -> int:
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        cur.execute(QUERY)
        rows = cur.fetchall()

    problems: list[str] = []
    checked = 0

    for (name, rls, forced, n_pol, has_tid, has_idx) in rows:
        if name in EXEMPT:
            continue
        if not has_tid:
            problems.append(f"{name}: no tenant_id column — is this intentional?")
            continue
        checked += 1
        if not rls:
            problems.append(f"{name}: RLS not enabled")
        if not forced:
            problems.append(f"{name}: RLS not FORCED (the owner role bypasses it)")
        if n_pol == 0:
            problems.append(f"{name}: RLS enabled but no policy defined")
        if not has_idx:
            problems.append(f"{name}: no index leading with tenant_id")

    if problems:
        print(f"FAIL — {len(problems)} issue(s) across {checked} tenant-scoped tables\n")
        for p in problems:
            print(f"  ✗ {p}")
        print("\nAdd the policy in the same migration as the table:")
        print("  ALTER TABLE <t> ENABLE ROW LEVEL SECURITY;")
        print("  ALTER TABLE <t> FORCE ROW LEVEL SECURITY;")
        print("  CREATE POLICY tenant_isolation ON <t>")
        print("      USING (tenant_id = current_setting('app.tenant_id', true)::uuid);")
        return 1

    print(f"OK — {checked} tenant-scoped tables, all protected")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    sys.exit(main(sys.argv[1]))
